drop table if exists tb_distributor_check;
CREATE TABLE `tb_distributor_check` (
  `id` bigint(20)  AUTO_INCREMENT COMMENT '自增ID',
  `distributor_id` varchar(64)  COMMENT '企业ID',
  `distributor_name` varchar(1024)  COMMENT '分销商名称',
  `legal_name` varchar(128)  COMMENT '法人姓名',
  `manager_name` varchar(128)  COMMENT '管理者姓名',
  `manager_uid` varchar(64)  COMMENT '管理者UID',
  `op_uid` varchar(32)  COMMENT '添加人UID',
  `op_name` varchar(128)  COMMENT '添加人名称',
  `user_uid` varchar(32)  COMMENT '用户UID',
  `user_name` varchar(128)  COMMENT '用户名称',
  `user_account` varchar(32)  COMMENT '用户账号',
  `distribution_range` int(11)  DEFAULT '0' COMMENT '配送范围',
  `points` varchar(1024)  COMMENT '配送点范围描点',
  `phones` varchar(256)  COMMENT '业务电话',
  `status` int(11)  DEFAULT '0' COMMENT '合作状态 0:正常 1:解除合作',
  `lbs_status` int(11)  DEFAULT '0' COMMENT 'lbs更新状态 0:未更新 1:已更新',
  `country_code` int(11)  DEFAULT '0' COMMENT '国家编码',
  `district_code` int(11)  DEFAULT '0' COMMENT '大区编码',
  `province_code` int(11)  DEFAULT '0' COMMENT '省份编码',
  `city_code` int(11)  DEFAULT '0' COMMENT '城市编码',
  `region_code` int(11)  DEFAULT '0' COMMENT '区域编码',
  `country` varchar(64)  DEFAULT '0' COMMENT '国家名称',
  `district` varchar(64)  DEFAULT '0' COMMENT '大区名称',
  `province` varchar(64)  DEFAULT '0' COMMENT '省名称',
  `city` varchar(64)  DEFAULT '0' COMMENT '城市名称',
  `region` varchar(64)  DEFAULT '0' COMMENT '区域名称',
  `details` varchar(128)  DEFAULT '0' COMMENT '详细地址',
  `longitude` double  DEFAULT '0' COMMENT '经度',
  `latitude` double  DEFAULT '0' COMMENT '纬度',
  `description` varchar(1024)  DEFAULT '0' COMMENT 'geo信息',
  `check_result` text  COMMENT '审核结果',
  `refuse_reason` text  COMMENT '拒绝理由',
  `check_user` varchar(32)  COMMENT '审核人UID',
  `check_user_name` varchar(32)  COMMENT '审核人名称',
  `check_status` int(11)  DEFAULT '0' COMMENT '0: 待审核 1: 审核完成',
  `check_time` datetime  COMMENT '审核时间',
  `check_type` varchar(32)  COMMENT 'add: 初审 update: 修改审核',
  `create_time` datetime  COMMENT '创建时间',
  `update_time` timestamp  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `distributor_id` (`distributor_id`),
  KEY `country_code` (`country_code`),
  KEY `district_code` (`district_code`),
  KEY `manager_uid` (`manager_uid`),
  KEY `user_uid` (`user_uid`),
  KEY `city_code` (`city_code`),
  KEY `region_code` (`region_code`),
  KEY `province_code` (`province_code`)
) ENGINE=InnoDB AUTO_INCREMENT=150 DEFAULT CHARSET=utf8 COMMENT='审核信息表'