drop table if exists tb_goods_info_new;
CREATE TABLE `tb_goods_info_new` (
  `goods_id` varchar(32)  COMMENT '自增ID',
  `goods_name` varchar(128)  COMMENT '商品名称',
  `goods_category` varchar(32)  COMMENT '商品分类',
  `goods_brand` varchar(64)  DEFAULT '' COMMENT '商品品牌',
  `goods_code` varchar(64)  DEFAULT '' COMMENT '商品条码',
  `sale_spec` varchar(32)  COMMENT '售卖规格',
  `goods_price` int(11)  COMMENT '商品价格',
  `goods_pic` varchar(1024)  COMMENT '商品图片',
  `goods_detail_url` varchar(128) ,
  `rank` int(11)  DEFAULT '0',
  `goods_sell_point` varchar(512)  COMMENT '商品卖点',
  `goods_recommend` tinyint(4)  DEFAULT '0',
  `hide` tinyint(4)  DEFAULT '0' COMMENT '是否隐藏商品',
  `goods_gift` varchar(128) ,
  `retail_goods_name` varchar(128)  DEFAULT '' COMMENT '零售商品名称',
  `retail_goods_code` varchar(64)  DEFAULT '' COMMENT '零售商品条码',
  `retail_spec` varchar(64)  COMMENT '零售包装规格',
  `retail_suggest_price` double  COMMENT '零售建议价格',
  `unit_capacity` varchar(32)  COMMENT '单位规格净含量',
  `unit_package_number` int(11)  COMMENT '包装内单位数量',
  `commission` double  COMMENT '商品提成',
  `gift` varchar(10240)  COMMENT '赠品策略',
  `goods_penetration` double  COMMENT '商品铺市奖励金额',
  `goods_version` int(11)  DEFAULT '0' COMMENT '商品版本',
  `status` int(11)  DEFAULT '0',
  `create_person` varchar(32)  COMMENT '创建人',
  `create_person_name` varchar(32)  COMMENT '创建人姓名',
  `create_time` timestamp  DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_person` varchar(32) DEFAULT NULL COMMENT '更新人',
  `update_person_name` varchar(32) DEFAULT NULL COMMENT '更新人姓名',
  `update_time` timestamp  DEFAULT '0000-00-00 00:00:00' COMMENT '更新时间',
  PRIMARY KEY (`goods_id`),
  UNIQUE KEY `goods_id` (`goods_id`),
  UNIQUE KEY `goods_code` (`goods_code`),
  UNIQUE KEY `t_unique_key` (`goods_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商品表'