drop table if exists tb_goods_info;
CREATE TABLE `tb_goods_info` (
  `goods_id` varchar(32)  COMMENT 'è‡ªå¢žID',
  `goods_name` varchar(128)  COMMENT 'å•†å“åç§°',
  `goods_category` varchar(32)  COMMENT 'å•†å“åˆ†ç±»',
  `goods_brand` varchar(64)  DEFAULT '' COMMENT 'å•†å“å“ç‰Œ',
  `goods_code` varchar(64)  DEFAULT '' COMMENT 'å•†å“æ¡ç ',
  `sale_spec` varchar(32)  COMMENT 'å”®å–è§„æ ¼',
  `goods_price` int(11)  COMMENT 'å•†å“ä»·æ ¼',
  `goods_pic` varchar(1024)  COMMENT 'å•†å“å›¾ç‰‡',
  `rank` int(11)  DEFAULT '0',
  `goods_detail_url` varchar(128) ,
  `retail_goods_name` varchar(128)  DEFAULT '' COMMENT 'é›¶å”®å•†å“åç§°',
  `retail_goods_code` varchar(64)  DEFAULT '' COMMENT 'é›¶å”®å•†å“æ¡ç ',
  `retail_spec` varchar(64)  COMMENT 'é›¶å”®åŒ…è£…è§„æ ¼',
  `retail_suggest_price` double  COMMENT '零售建议价格',
  `unit_capacity` varchar(32)  COMMENT 'å•ä½è§„æ ¼å‡€å«é‡',
  `unit_package_number` int(11)  COMMENT 'åŒ…è£…å†…å•ä½æ•°é‡',
  `commission` double  COMMENT 'å•†å“ææˆ',
  `commission_amount_distributor` double(12,2)  DEFAULT '0.00' COMMENT '经销商提供的提成金额',
  `commission_fee_distributor` double(12,2)  DEFAULT '0.00' COMMENT '经销商提供的提成费用',
  `commission_amount_subside_plateform` double(12,2)  DEFAULT '0.00' COMMENT '平台提供的提成补贴',
  `gift` varchar(10240)  COMMENT '赠品策略',
  `goods_penetration` double  COMMENT 'é“ºå¸‚å¥–åŠ±é‡‘é¢',
  `penetration_amount_distributor` double(12,2)  DEFAULT '0.00' COMMENT '经销商提供的铺市奖励金额',
  `penetration_fee_distributor` double(12,2)  DEFAULT '0.00' COMMENT '经销商提供的铺市奖励费用',
  `penetration_amount_subside_plateform` double(12,2)  DEFAULT '0.00' COMMENT '平台提供的铺市奖励补贴',
  `goods_sell_point` varchar(512)  COMMENT '商品卖点',
  `goods_recommend` tinyint(4)  DEFAULT '0',
  `hide` tinyint(4)  DEFAULT '0' COMMENT 'æ˜¯å¦éšè—å•†å“',
  `goods_gift` varchar(128) ,
  `goods_version` int(11)  DEFAULT '0' COMMENT 'å•†å“ç‰ˆæœ¬',
  `status` int(11)  DEFAULT '0',
  `create_person` varchar(32)  COMMENT 'åˆ›å»ºäºº',
  `create_person_name` varchar(32)  COMMENT '创建人姓名',
  `create_time` datetime  COMMENT '更新时间',
  `update_person` varchar(32) DEFAULT NULL COMMENT 'æ›´æ–°äºº',
  `update_person_name` varchar(32)  COMMENT '更新人姓名',
  `update_time` timestamp  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`goods_id`),
  UNIQUE KEY `goods_id` (`goods_id`),
  UNIQUE KEY `t_unique_key` (`goods_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='商品表'