drop table if exists tb_order;
CREATE TABLE `tb_order` (
  `order_id` varchar(32)  COMMENT '订单ID',
  `group_id` varchar(32)  DEFAULT '' COMMENT '组合ID',
  `place_user_id` varchar(32)  DEFAULT '' COMMENT '下单业务员ID',
  `total_amount` double(12,2)  DEFAULT '0.00' COMMENT '订单总金额',
  `commission_amount` double(12,2)  DEFAULT '0.00' COMMENT '针对订单的提成金额',
  `total_commission_amount` double(12,2)  DEFAULT '0.00' COMMENT '提成总金额',
  `total_commission_amount_by_distributor` double(12,2)  DEFAULT '0.00' COMMENT '经销商出的提成金额',
  `total_commission_fee_by_distributor` double(12,2)  DEFAULT '0.00' COMMENT '经销商提供的费用',
  `total_commission_amount_subside_plateform` double(12,2)  DEFAULT '0.00' COMMENT '平台补贴的提成',
  `total_commission_profit` double(12,2)  DEFAULT '0.00' COMMENT '提成方面都额利润',
  `total_penetration_amount` double(12,2)  DEFAULT '0.00' COMMENT '订单总铺市奖励金额',
  `total_penetration_amount_by_distributor` double(12,2)  DEFAULT '0.00' COMMENT '经销商提供的铺市金额',
  `total_penetration_fee_by_distributor` double(12,2)  DEFAULT '0.00' COMMENT '经销商提供的铺市的费用',
  `total_penetration_amount_subside_plateform` double(12,2)  DEFAULT '0.00' COMMENT '平台给的铺市的补贴',
  `total_penetration_profit` double(12,2)  DEFAULT '0.00' COMMENT '铺市方面的利润',
  `fetch_total_penetration_amount` double(12,2)  DEFAULT '0.00' COMMENT '获取的订单总铺市奖励金额',
  `fetch_total_penetration_amount_by_distributor` double(12,2)  DEFAULT '0.00' COMMENT '获取的经销商提供的铺市金额',
  `fetch_total_penetration_fee_by_distributor` double(12,2)  DEFAULT '0.00' COMMENT '获取的经销商提供的铺市的费用',
  `fetch_total_penetration_amount_subside_plateform` double(12,2)  DEFAULT '0.00' COMMENT '获取的平台给的铺市的补贴',
  `give_free_content` text  COMMENT '赠送内容',
  `goods_detail_number` int(11)  DEFAULT '0' COMMENT '订单中包含的商品种类数量',
  `over_view` text  COMMENT '概述',
  `status` tinyint(4)  DEFAULT '0' COMMENT '状态',
  `create_time` datetime  DEFAULT '0000-00-00 00:00:00' COMMENT '下单时间',
  `expried_time` datetime  DEFAULT '0000-00-00 00:00:00' COMMENT '过期时间',
  `cancel_time` datetime  DEFAULT '0000-00-00 00:00:00' COMMENT '取消时间',
  `update_time` timestamp  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `send_time` datetime  DEFAULT '0000-00-00 00:00:00' COMMENT '发货时间',
  `send_user_uid` varchar(32)  DEFAULT '' COMMENT '发货人员用户UID',
  `send_user_name` varchar(128)  DEFAULT '' COMMENT '发货人员姓名',
  `send_user_tel` varchar(128)  DEFAULT '' COMMENT '发货人电话',
  `cancel_user_uid` varchar(32)  DEFAULT '' COMMENT '用户UID',
  `cancel_user_name` varchar(128)  DEFAULT '' COMMENT '取消订单人姓名',
  `cancel_user_tel` varchar(128)  DEFAULT '' COMMENT '取消订单人电话',
  `cancel_user_type` varchar(32)  DEFAULT '' COMMENT '取消订单人是配送点还是业务员',
  `cancel_remark` varchar(128)  DEFAULT '' COMMENT '取消备注',
  `order_remark` varchar(128)  DEFAULT '' COMMENT '订单备注',
  `check_user_uid` varchar(32)  DEFAULT '' COMMENT '审核员UID',
  `check_time` datetime  DEFAULT '0000-00-00 00:00:00' COMMENT '审核时间',
  `check_remark` varchar(128)  DEFAULT '' COMMENT '审核标识',
  `check_flag` tinyint(4)  DEFAULT '0' COMMENT '0：未审核， 1：审核通过， 2：审核未通过， 3：审核部分通过',
  `receive_commission_money_time` datetime  DEFAULT '0000-00-00 00:00:00' COMMENT '获取提成奖励时间',
  `receive_penetration_money_time` datetime  DEFAULT '0000-00-00 00:00:00' COMMENT '审核铺市奖励时间',
  `determinate_user_uid` varchar(32)  DEFAULT '' COMMENT '核查员UID',
  `determinate_time` datetime  DEFAULT '0000-00-00 00:00:00' COMMENT '核查时间',
  `determinate_finish_time` datetime  DEFAULT '0000-00-00 00:00:00' COMMENT '核查完成时间',
  `determinate_reason` varchar(128)  DEFAULT '' COMMENT '核查原因',
  `determinate_remark` varchar(128)  DEFAULT '' COMMENT '核查标识',
  `determinate_flag` tinyint(4)  DEFAULT '0' COMMENT '0：不涉及核查， 1：核查通过 2：核查未通过',
  `data_version` int(11)  DEFAULT '0' COMMENT '数据版本',
  `place_user_name` varchar(128)  DEFAULT '' COMMENT '下单业务员姓名',
  `place_user_tel` varchar(128)  DEFAULT '' COMMENT '下单业务员电话',
  `place_user_name_pys` varchar(32)  DEFAULT '' COMMENT '下单业务员姓名拼音',
  `place_user_nick_name` varchar(128)  DEFAULT '' COMMENT '下单业务员昵称',
  `place_user_nick_name_pys` varchar(32)  DEFAULT '' COMMENT '下单业务员昵称拼音',
  `place_user_id_type` int(11)  DEFAULT '0' COMMENT '下单业务员身份证类型',
  `place_user_identity` varchar(128)  DEFAULT '' COMMENT '下单业务员身份证',
  `distributor_id` varchar(64)  DEFAULT '' COMMENT '配送点企业ID',
  `distributor_name` varchar(1024)  DEFAULT '' COMMENT '分销商名称',
  `distributor_legal_name` varchar(128)  DEFAULT '' COMMENT '配送点法人姓名',
  `distribution_range` int(11)  DEFAULT '0' COMMENT '配送点配送范围',
  `distributor_status` int(11)  DEFAULT '0' COMMENT '合作状态',
  `distributor_country_code` int(11)  DEFAULT '0' COMMENT '配送点国家编码',
  `distributor_district_code` int(11)  DEFAULT '0' COMMENT '配送点大区编码',
  `distributor_province_code` int(11)  DEFAULT '0' COMMENT '配送点省份编码',
  `distributor_city_code` int(11)  DEFAULT '0' COMMENT '配送点城市编码',
  `distributor_region_code` int(11)  DEFAULT '0' COMMENT '配送点区域编码',
  `distributor_country` varchar(64)  DEFAULT '0' COMMENT '配送点国家名称',
  `distributor_district` varchar(64)  DEFAULT '0' COMMENT '配送点大区名称',
  `distributor_province` varchar(64)  DEFAULT '0' COMMENT '配送点省名称',
  `distributor_city` varchar(64)  DEFAULT '0' COMMENT '配送点城市名称',
  `distributor_region` varchar(64)  DEFAULT '0' COMMENT '配送点区域名称',
  `distributor_details` varchar(128)  DEFAULT '0' COMMENT '配送点详细地址',
  `distributor_longitude` double  DEFAULT '0' COMMENT '配送点经度',
  `distributor_latitude` double  DEFAULT '0' COMMENT '配送点纬度',
  `distributor_tel` varchar(64)  DEFAULT '0' COMMENT '配送点电话号码',
  `terminal_id` varchar(32)  DEFAULT '' COMMENT '终端ID',
  `terminal_name` varchar(256)  DEFAULT '' COMMENT '终端名字',
  `terminal_shopkeeper_mobile` varchar(16)  DEFAULT '' COMMENT '终端联系手机',
  `terminal_shopkeeper_phone` varchar(16)  DEFAULT '' COMMENT '终端联系座机',
  `terminal_shopkeeper_name` varchar(64)  DEFAULT '' COMMENT '终端老板姓名',
  `terminal_shop_picture` varchar(64)  DEFAULT '' COMMENT '终端店头照key',
  `terminal_province_code` varchar(16)  DEFAULT '0' COMMENT '终端省份编码',
  `terminal_city_code` varchar(16)  DEFAULT '0' COMMENT '终端城市编码',
  `terminal_region_code` varchar(16)  DEFAULT '0' COMMENT '终端区域编码',
  `terminal_province` varchar(64)  DEFAULT '' COMMENT '终端省名称',
  `terminal_city` varchar(64)  DEFAULT '' COMMENT '终端城市名称',
  `terminal_region` varchar(64)  DEFAULT '' COMMENT '终端区域名称',
  `terminal_details` varchar(128)  DEFAULT '' COMMENT '终端详细地址',
  `terminal_longitude` double  DEFAULT '0' COMMENT '终端经度',
  `terminal_latitude` double  DEFAULT '0' COMMENT '终端纬度',
  `terminal_tel` double  DEFAULT '0' COMMENT '终端电话',
  `terminal_description` varchar(1024)  DEFAULT '' COMMENT '终端geo信息',
  `terminal_first_spell` varchar(128)  DEFAULT '' COMMENT '终端店名拼音首字母',
  `terminal_full_spell` varchar(600)  DEFAULT '' COMMENT '终端店名全部拼音',
  `terminal_add_uid` varchar(32)  DEFAULT '' COMMENT '终端添加者UID',
  `terminal_status` int(11)  DEFAULT '0' COMMENT '终端状态标识',
  `order_entry_type` tinyint(4)  DEFAULT '0' COMMENT '远程下单标识，0：附近下单， 1：远程下单',
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单表'