drop table if exists tb_order_goods_detail;
CREATE TABLE `tb_order_goods_detail` (
  `order_id` varchar(32)  COMMENT '订单ID',
  `group_id` varchar(32)  DEFAULT '' COMMENT '组合ID',
  `price` double(12,2)  DEFAULT '0.00' COMMENT '商品价格',
  `buy_number` int(11)  DEFAULT '0' COMMENT '购买数量',
  `give_free_number` int(11)  DEFAULT '0' COMMENT '赠送数量',
  `amount` double(12,2)  DEFAULT '0.00' COMMENT '金额',
  `commission_amount` double(12,2)  DEFAULT '0.00' COMMENT '提成金额',
  `commission_amount_distributor` double(12,2)  DEFAULT '0.00' COMMENT 'ç»é”€å•†æä¾›çš„ææˆé‡‘é¢',
  `commission_fee_distributor` double(12,2)  DEFAULT '0.00' COMMENT 'ç»é”€å•†æä¾›çš„ææˆè´¹ç”¨',
  `commission_amount_subside_plateform` double(12,2)  DEFAULT '0.00' COMMENT 'å¹³å°æä¾›çš„ææˆè¡¥è´´',
  `commission_profit` double(12,2)  DEFAULT '0.00' COMMENT 'ææˆæ–¹é¢çš„åˆ©æ¶¦',
  `give_free_content` text  COMMENT '赠送内容',
  `is_penetration` int(11)  DEFAULT '0' COMMENT '是否有铺市奖励',
  `penetration_amount` double(12,2)  DEFAULT '0.00' COMMENT '铺市奖励金额',
  `penetration_amount_distributor` double(12,2)  DEFAULT '0.00' COMMENT 'ç»é”€å•†æä¾›çš„é“ºå¸‚å¥–åŠ±é‡‘é¢',
  `penetration_fee_distributor` double(12,2)  DEFAULT '0.00' COMMENT 'ç»é”€å•†æä¾›çš„é“ºå¸‚å¥–åŠ±è´¹ç”¨',
  `penetration_amount_subside_plateform` double(12,2)  DEFAULT '0.00' COMMENT 'å¹³å°æä¾›çš„é“ºå¸‚å¥–åŠ±è¡¥è´´',
  `penetration_profit` double(12,2)  DEFAULT '0.00' COMMENT 'é“ºå¸‚å¥–åŠ±åˆ©æ¶¦',
  `fetch_penetration_amount` double(12,2)  DEFAULT '0.00' COMMENT '获取的铺市奖励金额',
  `fetch_penetration_amount_distributor` double(12,2)  DEFAULT '0.00' COMMENT 'ç»é”€å•†æä¾›çš„é“ºå¸‚å¥–åŠ±è´¹ç”¨',
  `fetch_penetration_fee_distributor` double(12,2)  DEFAULT '0.00' COMMENT 'å¹³å°æä¾›çš„é“ºå¸‚å¥–åŠ±è¡¥è´´',
  `fetch_penetration_amount_subside_plateform` double(12,2)  DEFAULT '0.00' COMMENT 'é“ºå¸‚å¥–åŠ±åˆ©æ¶¦',
  `check_remark` varchar(128)  DEFAULT '' COMMENT '审核标识',
  `check_flag` tinyint(4)  DEFAULT '0' COMMENT '0：未审核， 1：审核通过， 2：审核未通过',
  `goods_id` varchar(32)  DEFAULT '' COMMENT '商品ID',
  `goods_name` varchar(128)  DEFAULT '' COMMENT '商品名称',
  `goods_category` varchar(32)  DEFAULT '' COMMENT '商品分类',
  `goods_brand` varchar(64)  DEFAULT '' COMMENT '商品品牌',
  `goods_code` varchar(64)  DEFAULT '' COMMENT '商品条码',
  `goods_sale_spec` varchar(32)  DEFAULT '' COMMENT '售卖规格',
  `goods_price` int(11)  DEFAULT '0' COMMENT '商品价格',
  `goods_pic` varchar(1024)  DEFAULT '' COMMENT '商品图片',
  `goods_gift` varchar(128)  DEFAULT '' COMMENT '商品赠品',
  `retail_goods_name` varchar(128)  DEFAULT '' COMMENT '零售商品名称',
  `retail_goods_code` varchar(64)  DEFAULT '' COMMENT '零售商品条码',
  `retail_spec` varchar(64)  DEFAULT '' COMMENT '零售包装规格',
  `unit_capacity` varchar(32)  DEFAULT '' COMMENT '单位规格净含量',
  `unit_package_number` int(11)  DEFAULT '0' COMMENT '包装内单位数量',
  `goods_version` int(11)  DEFAULT '0' COMMENT '商品版本',
  `update_time` timestamp  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'æ›´æ–°æ—¶é—´',
  PRIMARY KEY (`order_id`,`goods_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='订单商品明细表'