drop table if exists tb_penetration_reset;
CREATE TABLE `tb_penetration_reset` (
  `id` bigint(20)  AUTO_INCREMENT COMMENT '自增ID',
  `terminal_id` varchar(32)  COMMENT '终端id',
  `goods_id` varchar(32)  COMMENT '商品id',
  `penetration_uid` varchar(32)  COMMENT '铺市者uid',
  `terminal_name` varchar(256)  DEFAULT '' COMMENT '终端名称',
  `penetration_name` varchar(128)  DEFAULT '' COMMENT '铺市者用户名',
  `distributor_id` varchar(32)  DEFAULT '' COMMENT '分销商ID',
  `distributor_name` varchar(128)  DEFAULT '' COMMENT '分销商名称',
  `business_id` varchar(64)  DEFAULT '' COMMENT '资金交易业务ID',
  `order_id` varchar(32)  COMMENT '达成铺市的订单ID',
  `goods_name` varchar(32)  COMMENT '商品名称',
  `place_time` datetime  COMMENT '下单时间',
  `send_time` datetime  COMMENT '发货时间',
  `money` decimal(16,2)  COMMENT '领取金额',
  `fee_distributor` decimal(16,2)  DEFAULT '0.00' COMMENT '平台支付金额',
  `amount_plateform` decimal(16,2)  DEFAULT '0.00' COMMENT '平台支付金额',
  `amount_distributor` decimal(16,2)  DEFAULT '0.00' COMMENT '分销商支付金额',
  `year` int(11)  DEFAULT '0' COMMENT '年份',
  `month` int(11)  DEFAULT '0' COMMENT '月份',
  `week` int(11)  DEFAULT '0' COMMENT '一年中的第几周',
  `award_time` datetime  COMMENT '铺市奖励时间',
  `order_status` int(11)  DEFAULT '0' COMMENT '订单状态(0:未发货  1:已发货  2:已取消)',
  `penetration_status` int(11)  DEFAULT '0' COMMENT '铺市状态(0:未铺市(待处理)  1:已铺市  2:终端被禁用铺市  3:订单已取消  4:订单消息异常  5:未上铺市功能  6:终端审核未通过 7:人为设置铺市占用)',
  `business_status` int(11)  DEFAULT '0' COMMENT '到帐状态(0:未到帐  1:已到帐)',
  `business_success_time` datetime  COMMENT '帐务处理成功时间',
  `data_version` int(11)  DEFAULT '0' COMMENT '数据版本',
  `create_time` datetime  COMMENT '创建时间',
  `update_time` timestamp  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `index_terminal_id` (`terminal_id`),
  KEY `index_order_id` (`order_id`),
  KEY `index_penetration_uid` (`penetration_uid`)
) ENGINE=InnoDB AUTO_INCREMENT=254 DEFAULT CHARSET=utf8 COMMENT='铺市重置记录表'