drop table if exists tb_terminal_check;
CREATE TABLE `tb_terminal_check` (
  `check_id` bigint(20)  AUTO_INCREMENT COMMENT '审核ID',
  `terminal_id` varchar(32)  COMMENT '终端ID',
  `terminal_name` varchar(256)  COMMENT '终端名字',
  `shopkeeper_mobile` varchar(16)  COMMENT '联系手机',
  `shopkeeper_phone` varchar(16)  DEFAULT '' COMMENT '联系座机',
  `shopkeeper_name` varchar(64)  COMMENT '老板姓名',
  `shop_picture` varchar(64)  COMMENT '店头照key',
  `province_code` int(11)  DEFAULT '0' COMMENT '省份编码',
  `city_code` int(11)  DEFAULT '0' COMMENT '城市编码',
  `region_code` int(11)  DEFAULT '0' COMMENT '区域编码',
  `province` varchar(64)  DEFAULT '' COMMENT '省名称',
  `city` varchar(64)  DEFAULT '' COMMENT '城市名称',
  `region` varchar(64)  DEFAULT '' COMMENT '区域名称',
  `details` varchar(128)  DEFAULT '' COMMENT '详细地址',
  `longitude` double  DEFAULT '0' COMMENT '经度',
  `latitude` double  DEFAULT '0' COMMENT '纬度',
  `description` varchar(1024)  DEFAULT '' COMMENT 'geo信息',
  `first_spell` varchar(128)  COMMENT '店名拼音首字母',
  `full_spell` varchar(600)  COMMENT '店名全部拼音',
  `main_type` int(11)  DEFAULT '0' COMMENT '大类型',
  `sub_type` int(11)  DEFAULT '0' COMMENT '小类型',
  `type_level` int(11)  DEFAULT '0' COMMENT '终端类型级别',
  `creator_uid` varchar(64)  COMMENT '终端创建人uid',
  `auditor_uid` varchar(64)  COMMENT '终端审核人人uid',
  `approve_result` int(10)  DEFAULT '0' COMMENT '审核结果（0-未审核; 1-通过; 2-待完善; 3-重复终端; 4-虚假店头照; 5-虚假定位; 6-其他原因）',
  `approve_time` datetime  COMMENT '审核时间',
  `remark` varchar(256)  COMMENT '审核理由',
  `is_send_order` int(11)  DEFAULT '0' COMMENT '是否有发货订单',
  `create_time` datetime  COMMENT '创建时间',
  `update_time` timestamp  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`check_id`),
  KEY `index_terminal_name` (`terminal_name`(255)),
  KEY `index_creator_uid` (`creator_uid`),
  KEY `index_auditor_uid` (`auditor_uid`),
  KEY `index_shopkeeper_name` (`shopkeeper_name`),
  KEY `index_shopkeeper_mobile` (`shopkeeper_mobile`)
) ENGINE=InnoDB AUTO_INCREMENT=5576 DEFAULT CHARSET=utf8 COMMENT='终端审核表'