drop table if exists tb_user_sale;
CREATE TABLE `tb_user_sale` (
  `uid` varchar(32)  COMMENT '用户ID',
  `name` varchar(128)  COMMENT '姓名',
  `name_pys` varchar(32)  COMMENT '姓名拼音首字母缩写',
  `nick_name` varchar(128)  COMMENT '昵称',
  `nick_name_pys` varchar(32)  COMMENT '昵称拼音首字母缩写',
  `id_type` int(11)  DEFAULT '0' COMMENT '证件类型 0=默认身份证',
  `id` varchar(128)  COMMENT '证件号码',
  `is_verify` int(11)  DEFAULT '0' COMMENT '是否认证标识: 0-未认证；1-已认证',
  `recommend_code` varchar(64)  COMMENT '推荐码',
  `is_bind_card` int(11)  DEFAULT '0' COMMENT '是否绑卡标识, 0-未绑定；1-已绑定',
  `referrer_uid` varchar(32) DEFAULT NULL COMMENT '推荐人uid',
  `first_login` int(11)  DEFAULT '0' COMMENT '是否首次登录，0：不是，1：是',
  `login_client` varchar(32)  DEFAULT '' COMMENT '登录终端平台，ios|android',
  `latitude` double  DEFAULT '0' COMMENT '纬度',
  `longitude` double  DEFAULT '0' COMMENT '经度',
  `description` varchar(1024)  DEFAULT '' COMMENT '用户定位信息描述',
  `province_code` int(11)  DEFAULT '0' COMMENT '省编码',
  `city_code` int(11)  DEFAULT '0' COMMENT '市编码',
  `region_code` int(11)  DEFAULT '0' COMMENT '区编码',
  `create_time` datetime  COMMENT '创建时间',
  `update_time` timestamp  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`uid`),
  UNIQUE KEY `recommend_code` (`recommend_code`),
  KEY `id_type` (`id_type`),
  KEY `id` (`id`),
  KEY `is_verify` (`is_verify`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='业务员个人信息表'